### ISSUE TITLE
Unable to find either executable 'empy' or Python module 'em'...  try   installing the package 'python-empy'

### ISSUE THREAD

**Issue by ysl208** [ysl208/iRoPro#59]
When running `catkin build` I get the following error
```
CMake Error at /opt/ros/melodic/share/catkin/cmake/empy.cmake:29 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python-empy'
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/all.cmake:163 (include)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:56 (find_package)
```

**Comment by ysl208** [comment]
This can be solved by telling it to use python3
```
catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m
```

**Comment by AnshShah3009** [comment]
Why doesn't it default to python3?

**Comment by AbdelrahmanAbounida** [comment]
`catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3`

**Comment by liu-jun-chen** [comment]
> `catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3`

Thanks! Your solution works for me!

**Comment by AwesomePeiweiPan** [comment]
> `catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3`

Yes, work for me too. Thanks a lot!

**Comment by Jeremiah-HL** [comment]
That works for me, too! Thanks!

**Comment by mnour12** [comment]
This is super old, but this might be helpful to someone.
Other than the solution mentioned by @ysl208  (which worked with me for a while until it broke again).
Root cause for this issue as far as i understand: Python environment conflict - ROS builds using system Python, but if you have conda/virtualenv active, catkin finds the wrong Python interpreter that doesn't have empy installed.
A more permanent solution would be to ensure that you're using system python for ROS projects and it's the correct version
